export const MANUAL_QUERIES = [
  { q: 'lavarropas', pattern: 'lavarrop', category: 'Lavarropas' },
  { q: 'heladera', pattern: 'heladera' },
  { q: 'freezer', pattern: 'freezer' },
  { q: 'microondas', pattern: 'microondas' },
  { q: 'aire acondicionado', pattern: 'aire acondicionado|split' },
  { q: 'ventilador', pattern: 'ventilador' },
  { q: 'calefactor', pattern: 'calefactor|caloventor' },
  { q: 'horno electrico', pattern: 'horno electrico|horno eléctrico' },
  { q: 'anafe', pattern: 'anafe' },
  { q: 'cocina', pattern: 'cocina' },
  { q: 'notebook', pattern: 'notebook|laptop|portatil|portátil', category: 'Notebooks' },
  { q: 'computadora', pattern: 'computadora|pc|desktop' },
  { q: 'monitor', pattern: 'monitor' },
  { q: 'teclado', pattern: 'teclado' },
  { q: 'mouse', pattern: 'mouse' },
  { q: 'tablet', pattern: 'tablet' },
  { q: 'impresora', pattern: 'impresora', category: 'Impresoras / multifunción' },
  { q: 'scanner', pattern: 'scanner|escaner|escáner' },
  { q: 'drone', pattern: 'drone', category: 'Drones' },
  { q: 'celular', pattern: 'celular|smartphone|telefono|teléfono' },
  { q: 'smart tv', pattern: 'smart tv|tv led|televisor', category: 'Smart TV y TV Led' },
  { q: 'parlante', pattern: 'parlante', category: 'Parlantes' },
  { q: 'auriculares', pattern: 'auricular' },
  { q: 'smartwatch', pattern: 'smartwatch|smart watch', category: 'Smart Watch' },
  { q: 'camara de seguridad', pattern: 'camara de seguridad|cámara de seguridad', category: 'Cámaras de Seguridad' },
  { q: 'camara deportiva', pattern: 'camara de accion|camara deportiva|cámara de acción' },
  { q: 'proyector', pattern: 'proyector' },
  { q: 'router', pattern: 'router|modem' },
  { q: 'disco externo', pattern: 'disco externo|disco rigido|disco rígido' },
  { q: 'pendrive', pattern: 'pendrive|pen drive|memoria usb' },
  { q: 'aspiradora robot', pattern: 'aspiradora', category: 'Aspiradoras Robot' },
  { q: 'aspiradora', pattern: 'aspiradora' },
  { q: 'licuadora', pattern: 'licuadora' },
  { q: 'batidora', pattern: 'batidora' },
  { q: 'cafetera', pattern: 'cafetera', category: 'Cafeteras' },
  { q: 'pava electrica', pattern: 'pava electrica|pava eléctrica' },
  { q: 'tostadora', pattern: 'tostadora' },
  { q: 'freidora de aire', pattern: 'freidora' },
  { q: 'sandwichera', pattern: 'sandwichera' },
  { q: 'plancha', pattern: 'plancha' },
  { q: 'masajeador', pattern: 'masajeador', category: 'Masajeadores' },
  { q: 'secador de pelo', pattern: 'secador de pelo|secador' },
  { q: 'afeitadora', pattern: 'afeitadora' },
  { q: 'depiladora', pattern: 'depiladora' },
  { q: 'balanza', pattern: 'balanza' },
  { q: 'tensiometro', pattern: 'tensiometro|tensiómetro' },
  { q: 'termometro', pattern: 'termometro|termómetro' },
  { q: 'nebulizador', pattern: 'nebulizador' },
  { q: 'mochila', pattern: 'mochila' },
  { q: 'valija', pattern: 'valija|maleta' },
  { q: 'silla gamer', pattern: 'silla gamer|silla g' },
  { q: 'escritorio', pattern: 'escritorio' },
  { q: 'organizador', pattern: 'organizador' },
  { q: 'bici', pattern: 'bicicleta|bici' },
  { q: 'cinta de correr', pattern: 'cinta de correr|cinta caminadora' },
  { q: 'bicicleta fija', pattern: 'bicicleta.*fija|spinning' },
  { q: 'pesa', pattern: 'pesa|mancuerna|barra' },
  { q: 'colchoneta', pattern: 'colchoneta|mat yoga' },
  { q: 'pelota', pattern: 'pelota' },
  { q: 'scooter', pattern: 'scooter|monopatin|monopatín' },
  { q: 'carpa', pattern: 'carpa' },
  { q: 'sombrilla', pattern: 'sombrilla|parasol' },
  { q: 'parrilla', pattern: 'parrilla' },
  { q: 'pileta', pattern: 'pileta' },
  { q: 'hidrolavadora', pattern: 'hidrolavadora' },
  { q: 'cortadora de cesped', pattern: 'cortadora de cesped|cortadora de césped' },
  { q: 'taladro', pattern: 'taladro' },
  { q: 'amoladora', pattern: 'amoladora' },
  { q: 'sierra', pattern: 'sierra' },
  { q: 'soldadora', pattern: 'soldador' },
  { q: 'compresor', pattern: 'compresor' },
  { q: 'generador', pattern: 'generador' },
  { q: 'linterna', pattern: 'linterna' },
  { q: 'termo', pattern: 'termo' },
  { q: 'vaso termico', pattern: 'vaso termico|vaso térmico' },
  { q: 'cuchillo', pattern: 'cuchillo' },
  { q: 'olla', pattern: 'olla' },
  { q: 'sarten', pattern: 'sarten|sartén' },
  { q: 'juego de herramientas', pattern: 'herramienta' },
  { q: 'purificador de aire', pattern: 'purificador' },
  { q: 'humidificador', pattern: 'humidificador' },
  { q: 'barrefondo', pattern: 'barrefondo|limpiafondo' },
  { q: 'robot piscina', pattern: 'robot.*piscina|barrefondo' },
  { q: 'gazebo', pattern: 'gazebo|quinche|quincho' },
  { q: 'reposera', pattern: 'reposera' },
  { q: 'mesa plegable', pattern: 'mesa plegable' },
  { q: 'silla plegable', pattern: 'silla plegable' },
  { q: 'cargador portatil', pattern: 'cargador portatil|power bank' },
  { q: 'funda celular', pattern: 'funda' },
  { q: 'tripode', pattern: 'tripode|trípode' },
  { q: 'microfono', pattern: 'microfono|micrófono' },
  { q: 'webcam', pattern: 'webcam' },
  { q: 'gimbal', pattern: 'gimbal|estabilizador' },
  { q: 'tabla grafica', pattern: 'tableta grafica|tabla grafica|grafica gadnic|wacom' },
  { q: 'gadnic', pattern: 'gadnic' },
  { q: 'dji', pattern: 'dji' },
  { q: 'samsung', pattern: 'samsung' },
  { q: 'philco', pattern: 'philco' },
  { q: 'hp', pattern: '\\bhp\\b' },
  { q: 'xiaomi', pattern: 'xiaomi' },
];
